// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbjpurniyjebdvwxzegf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFianB1cm5peWplYmR2d3h6ZWdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MzgyNTksImV4cCI6MjA2MDIxNDI1OX0.yl5inTAMnoxLO38rbZ7QISDTGKXLQSyppiLLa5dGAeM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);